require("dotenv").config();

module.exports = {
  DISCORD_TOKEN: process.env.DISCORD_TOKEN,
  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID,
  ADMIN_DASHBOARD_CHANNEL_ID: process.env.ADMIN_DASHBOARD_CHANNEL_ID,
  CREATOR_LOG_CHANNEL_ID: process.env.CREATOR_LOG_CHANNEL_ID,
  SUBMISSIONS_LOG_CHANNEL_ID: process.env.SUBMISSIONS_LOG_CHANNEL_ID,
  BOT_ALERTS_CHANNEL_ID: process.env.BOT_ALERTS_CHANNEL_ID,
  SUPABASE_URL: process.env.SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  SHOPIFY_API_KEY: process.env.SHOPIFY_API_KEY,
  SHOPIFY_API_SECRET: process.env.SHOPIFY_API_SECRET,
  SHOPIFY_WEBHOOK_SECRET: process.env.SHOPIFY_WEBHOOK_SECRET,
  SHOPIFY_SCOPES: process.env.SHOPIFY_SCOPES || 'read_orders,read_customers',
  SHOPIFY_APP_URL: process.env.SHOPIFY_APP_URL || process.env.PUBLIC_BASE_URL || 'http://localhost:3000',
  ARIA_WELLNESS_TEST_PRODUCT_VARIANT_ID: process.env.ARIA_WELLNESS_TEST_PRODUCT_VARIANT_ID,
  NOVO_LOOM_GUMMIES_VARIANT_ID: process.env.NOVO_LOOM_GUMMIES_VARIANT_ID,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
  PAYOUT_MODE: process.env.PAYOUT_MODE || 'claims_disabled',
  NODE_ENV: process.env.NODE_ENV || "development",
  DEFAULT_REF_TEMPLATE: process.env.DEFAULT_REF_TEMPLATE,
  PUBLIC_BASE_URL: process.env.PUBLIC_BASE_URL || 'http://localhost:3000',
  EXPORTS_DIR: process.env.EXPORTS_DIR,
  LOG_LEVEL: process.env.LOG_LEVEL || "info"
};
