-- PartnerLinks Phase 1: Referral Tracking Tables
-- Migration: 001_tracking_tables.sql
-- Safe to rerun (idempotent)

-- Create clicks table to track referral link clicks
CREATE TABLE IF NOT EXISTS clicks (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  brand_id bigint not null references brands(id) on delete cascade,
  creator_id bigint not null references creators(id) on delete cascade,
  session_id text not null,
  ip_hash text,
  user_agent text,
  referrer text,
  destination_url text
);

-- Create index on brand_id for filtering clicks by brand
CREATE INDEX IF NOT EXISTS idx_clicks_brand_id ON clicks(brand_id);

-- Create index on creator_id for filtering clicks by creator
CREATE INDEX IF NOT EXISTS idx_clicks_creator_id ON clicks(creator_id);

-- Create index on session_id for session-based queries
CREATE INDEX IF NOT EXISTS idx_clicks_session_id ON clicks(session_id);

-- Create attribution_sessions table to track creator attribution per session
CREATE TABLE IF NOT EXISTS attribution_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  brand_id bigint not null references brands(id) on delete cascade,
  session_id text not null,
  current_creator_id bigint references creators(id) on delete set null,
  last_click_id bigint references clicks(id) on delete set null,
  unique(brand_id, session_id)
);

-- Create index on (brand_id, session_id) for fast session lookups
CREATE INDEX IF NOT EXISTS idx_attribution_sessions_brand_session ON attribution_sessions(brand_id, session_id);

-- Safe alterations to existing tables
ALTER TABLE brands ADD COLUMN IF NOT EXISTS destination_url text;
ALTER TABLE creators ADD COLUMN IF NOT EXISTS tracking_link text;

-- Migration complete
