-- PartnerLinks Phase 2: Sales Conversion Tracking
-- Migration: 002_conversions_table.sql
-- Safe to rerun (idempotent)

CREATE TABLE IF NOT EXISTS conversions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  brand_id bigint references brands(id) on delete cascade,
  creator_id bigint references creators(id) on delete set null,
  attribution_session_id bigint references attribution_sessions(id) on delete set null,
  click_id bigint references clicks(id) on delete set null,
  session_id text,
  order_id text,
  order_value numeric,
  currency text default 'USD',
  commission_rate numeric,
  commission_amount numeric,
  source text default 'manual',
  notes text
);

CREATE INDEX IF NOT EXISTS idx_conversions_brand_id ON conversions(brand_id);
CREATE INDEX IF NOT EXISTS idx_conversions_creator_id ON conversions(creator_id);
CREATE INDEX IF NOT EXISTS idx_conversions_attribution_session_id ON conversions(attribution_session_id);
CREATE INDEX IF NOT EXISTS idx_conversions_click_id ON conversions(click_id);
CREATE INDEX IF NOT EXISTS idx_conversions_session_id ON conversions(session_id);
CREATE INDEX IF NOT EXISTS idx_conversions_order_id ON conversions(order_id);
CREATE INDEX IF NOT EXISTS idx_conversions_created_at ON conversions(created_at);
CREATE INDEX IF NOT EXISTS idx_conversions_brand_creator ON conversions(brand_id, creator_id);

-- Migration complete
