-- PartnerLinks Phase 3: Creator Network Referral Economics
-- Migration: 003_creator_network.sql
-- Safe to rerun (idempotent)

ALTER TABLE creators ADD COLUMN IF NOT EXISTS referral_code text;
ALTER TABLE creators ADD COLUMN IF NOT EXISTS parent_creator_id bigint references creators(id) on delete set null;
ALTER TABLE creators ADD COLUMN IF NOT EXISTS referred_at timestamptz;
ALTER TABLE creators ADD COLUMN IF NOT EXISTS join_referral_link text;

-- Platform fee is PartnerLinks-owned revenue. Creator-network overrides are calculated from this only.
ALTER TABLE conversions ADD COLUMN IF NOT EXISTS platform_fee_amount numeric default 0;

UPDATE creators
SET referral_code = creator_code
WHERE referral_code IS NULL;

CREATE TABLE IF NOT EXISTS creator_invite_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  inviter_creator_id bigint references creators(id) on delete cascade,
  session_id text not null,
  ip_hash text,
  user_agent text,
  referrer text,
  invite_code text
);

CREATE TABLE IF NOT EXISTS creator_network_earnings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  earning_creator_id bigint references creators(id) on delete cascade,
  source_creator_id bigint references creators(id) on delete cascade,
  conversion_id bigint references conversions(id) on delete cascade,
  platform_fee_amount numeric,
  commission_rate numeric,
  commission_amount numeric,
  level int,
  notes text
);

CREATE INDEX IF NOT EXISTS idx_creators_referral_code ON creators(referral_code);
CREATE INDEX IF NOT EXISTS idx_creators_parent_creator_id ON creators(parent_creator_id);
CREATE INDEX IF NOT EXISTS idx_creator_invite_sessions_inviter_creator_id ON creator_invite_sessions(inviter_creator_id);
CREATE INDEX IF NOT EXISTS idx_creator_invite_sessions_session_id ON creator_invite_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_creator_network_earnings_earning_creator_id ON creator_network_earnings(earning_creator_id);
CREATE INDEX IF NOT EXISTS idx_creator_network_earnings_source_creator_id ON creator_network_earnings(source_creator_id);
CREATE INDEX IF NOT EXISTS idx_creator_network_earnings_conversion_id ON creator_network_earnings(conversion_id);
CREATE INDEX IF NOT EXISTS idx_creator_network_earnings_level ON creator_network_earnings(level);

-- Migration complete
