-- PartnerLinks Phase 5: Shopify Store Installs
-- Migration: 005_shopify_stores.sql
-- Safe to rerun (idempotent)

CREATE TABLE IF NOT EXISTS shopify_stores (
  id bigint generated by default as identity primary key,
  brand_id bigint references brands(id) on delete set null,
  shop_domain text not null,
  access_token text not null,
  installed_at timestamptz default now() not null,
  created_at timestamptz default now() not null
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_shopify_stores_shop_domain_unique ON shopify_stores(shop_domain);
CREATE INDEX IF NOT EXISTS idx_shopify_stores_brand_id ON shopify_stores(brand_id);
CREATE INDEX IF NOT EXISTS idx_shopify_stores_installed_at ON shopify_stores(installed_at);

-- Migration complete
