-- PartnerLinks Phase 7: Brand-Origin Network Sponsorship
-- Migration: 007_brand_origin_network.sql
-- Safe to rerun (idempotent)

ALTER TABLE creators ADD COLUMN IF NOT EXISTS invited_by_brand_id bigint references brands(id) on delete set null;
ALTER TABLE creators ADD COLUMN IF NOT EXISTS brand_referred_at timestamptz;

CREATE TABLE IF NOT EXISTS brand_network_earnings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  earning_brand_id bigint references brands(id) on delete cascade,
  source_creator_id bigint references creators(id) on delete cascade,
  conversion_id bigint references conversions(id) on delete cascade,
  platform_fee_amount numeric,
  commission_rate numeric,
  commission_amount numeric,
  level int,
  notes text
);

CREATE INDEX IF NOT EXISTS idx_creators_invited_by_brand_id ON creators(invited_by_brand_id);
CREATE INDEX IF NOT EXISTS idx_brand_network_earnings_earning_brand_id ON brand_network_earnings(earning_brand_id);
CREATE INDEX IF NOT EXISTS idx_brand_network_earnings_source_creator_id ON brand_network_earnings(source_creator_id);
CREATE INDEX IF NOT EXISTS idx_brand_network_earnings_conversion_id ON brand_network_earnings(conversion_id);
CREATE INDEX IF NOT EXISTS idx_brand_network_earnings_level ON brand_network_earnings(level);

-- Migration complete
