-- PartnerLinks: Shopify Webhook Attribution Diagnostics
-- Migration: 014_shopify_attribution_events.sql
-- Safe to rerun (idempotent)

CREATE TABLE IF NOT EXISTS shopify_attribution_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  order_id text,
  shopify_order_id text,
  shop_domain text,
  brand_id bigint references brands(id) on delete set null,
  matched_creator_id bigint references creators(id) on delete set null,
  matched_creator_code text,
  matched_product_slug text,
  partnerlinks_ref text,
  attribution_source text,
  attribution_confidence text,
  fallback_used boolean default false not null,
  recent_click_id bigint references clicks(id) on delete set null,
  click_id bigint references clicks(id) on delete set null,
  session_id text,
  time_delta_from_click_seconds int,
  decision text,
  unmatched_reason text,
  duplicate_order boolean default false not null,
  conversion_id bigint references conversions(id) on delete set null,
  checked_sources jsonb default '[]'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_order_id ON shopify_attribution_events(order_id);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_shopify_order_id ON shopify_attribution_events(shopify_order_id);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_shop_domain ON shopify_attribution_events(shop_domain);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_brand_id ON shopify_attribution_events(brand_id);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_creator_code ON shopify_attribution_events(matched_creator_code);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_partnerlinks_ref ON shopify_attribution_events(partnerlinks_ref);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_source ON shopify_attribution_events(attribution_source);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_decision ON shopify_attribution_events(decision);
CREATE INDEX IF NOT EXISTS idx_shopify_attr_events_created_at ON shopify_attribution_events(created_at);

-- Migration complete
