-- PartnerLinks Phase 15: Brand Invite Session Audit Trail
-- Migration: 015_brand_invite_sessions.sql
-- Safe to rerun (idempotent)

CREATE TABLE IF NOT EXISTS brand_invite_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  inviting_brand_id bigint references brands(id) on delete cascade,
  session_id text not null,
  ip_hash text,
  user_agent text,
  referrer text,
  invite_code text,
  resulting_creator_id bigint references creators(id) on delete set null,
  bound_at timestamptz,
  notes text
);

CREATE INDEX IF NOT EXISTS idx_brand_invite_sessions_inviting_brand_id ON brand_invite_sessions(inviting_brand_id);
CREATE INDEX IF NOT EXISTS idx_brand_invite_sessions_session_id ON brand_invite_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_brand_invite_sessions_invite_code ON brand_invite_sessions(invite_code);
CREATE INDEX IF NOT EXISTS idx_brand_invite_sessions_resulting_creator_id ON brand_invite_sessions(resulting_creator_id);

-- Migration complete
