-- PartnerLinks Phase 16: Financial Reversal Ledger
-- Migration: 016_financial_reversal_ledger.sql
-- Safe to rerun (idempotent)
--
-- Purpose:
--   Creates additive accounting/audit infrastructure for refunds, partial refunds,
--   chargebacks, disputes, manual adjustments, future negative-balance offsets,
--   and future reversal application.
--
-- Important:
--   This migration does NOT change dashboard totals, payout_status, claim logic,
--   Stripe transfers, settlement behavior, attribution behavior, or existing
--   conversion/earning rows. It only creates immutable reversal observability
--   and accounting tables.

CREATE TABLE IF NOT EXISTS financial_reversal_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,

  idempotency_key text not null,
  source_system text not null,
  source_event_id text,

  brand_id bigint references brands(id) on delete set null,
  shop_domain text,
  order_id text,
  shopify_order_id text,
  conversion_id bigint references conversions(id) on delete set null,

  reversal_type text not null,
  reversal_reason text,
  reversal_status text not null default 'detected',

  currency text default 'USD' not null,
  original_order_amount numeric(12, 2),
  reversed_order_amount numeric(12, 2),
  reversal_ratio numeric(8, 6),

  evidence jsonb default '{}'::jsonb not null,
  notes text,

  constraint chk_financial_reversal_events_source_system
    check (source_system in ('shopify', 'stripe', 'admin', 'manual')),
  constraint chk_financial_reversal_events_reversal_type
    check (reversal_type in ('refund', 'partial_refund', 'chargeback', 'dispute', 'manual_adjustment')),
  constraint chk_financial_reversal_events_reversal_status
    check (reversal_status in ('detected', 'pending_review', 'applied', 'ignored', 'failed')),
  constraint chk_financial_reversal_events_reversal_ratio
    check (reversal_ratio is null or (reversal_ratio >= 0 and reversal_ratio <= 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_financial_reversal_events_idempotency_key
  ON financial_reversal_events(idempotency_key);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_created_at
  ON financial_reversal_events(created_at);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_source
  ON financial_reversal_events(source_system, source_event_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_brand_id
  ON financial_reversal_events(brand_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_shop_domain
  ON financial_reversal_events(shop_domain);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_order_id
  ON financial_reversal_events(order_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_shopify_order_id
  ON financial_reversal_events(shopify_order_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_conversion_id
  ON financial_reversal_events(conversion_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_events_status
  ON financial_reversal_events(reversal_status);

CREATE TABLE IF NOT EXISTS financial_reversal_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,

  reversal_event_id bigint not null references financial_reversal_events(id) on delete cascade,

  item_type text not null,
  conversion_id bigint references conversions(id) on delete set null,
  creator_network_earning_id bigint references creator_network_earnings(id) on delete set null,
  brand_network_earning_id bigint references brand_network_earnings(id) on delete set null,
  creator_earning_claim_id uuid references creator_earning_claims(id) on delete set null,

  affected_creator_id bigint references creators(id) on delete set null,
  affected_brand_id bigint references brands(id) on delete set null,

  original_amount numeric(12, 2),
  reversed_amount numeric(12, 2) not null default 0,
  currency text default 'USD' not null,

  payout_status_at_reversal text,
  settlement_status_at_reversal text,

  offset_required boolean default false not null,
  offset_status text default 'none' not null,

  notes text,

  constraint chk_financial_reversal_items_item_type
    check (item_type in ('direct_commission', 'platform_fee', 'creator_network_override', 'brand_network_override', 'claim_offset')),
  constraint chk_financial_reversal_items_offset_status
    check (offset_status in ('none', 'pending', 'required', 'applied', 'ignored', 'failed')),
  constraint chk_financial_reversal_items_reversed_amount
    check (reversed_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_event_id
  ON financial_reversal_items(reversal_event_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_item_type
  ON financial_reversal_items(item_type);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_conversion_id
  ON financial_reversal_items(conversion_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_creator_network_earning_id
  ON financial_reversal_items(creator_network_earning_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_brand_network_earning_id
  ON financial_reversal_items(brand_network_earning_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_creator_earning_claim_id
  ON financial_reversal_items(creator_earning_claim_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_affected_creator_id
  ON financial_reversal_items(affected_creator_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_affected_brand_id
  ON financial_reversal_items(affected_brand_id);

CREATE INDEX IF NOT EXISTS idx_financial_reversal_items_offset_required
  ON financial_reversal_items(offset_required);

COMMENT ON TABLE financial_reversal_events IS
  'Immutable PartnerLinks refund/chargeback/dispute/manual-adjustment event ledger. Observability/accounting infrastructure only; does not apply reversals or move money by itself.';

COMMENT ON TABLE financial_reversal_items IS
  'Line-item reversal ledger linking reversal events to affected conversion, network earning, brand earning, or claim rows. Does not mutate payout behavior by itself.';

COMMENT ON COLUMN financial_reversal_events.evidence IS
  'Minimal non-sensitive evidence only. Do not store full Shopify, Stripe, customer, card, or payment payloads here by default.';

-- Migration complete
