-- PartnerLinks: Imported Product Feed Items
-- Migration: 021_product_feed_items.sql
-- Safe to rerun (idempotent)
-- Stores product destinations only. Does not modify referral, invite, commission, or attribution logic.

CREATE TABLE IF NOT EXISTS product_feed_items (
  id bigint generated by default as identity primary key,
  source text not null,
  brand_slug text not null,
  product_slug text not null,
  product_name text not null,
  description text,
  image_url text,
  price numeric,
  currency text,
  merchant_name text,
  merchant_category text,
  aw_deep_link text,
  destination_url text,
  external_product_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  imported_at timestamptz not null default now(),
  unique(source, brand_slug, product_slug)
);

CREATE INDEX IF NOT EXISTS idx_product_feed_items_lookup
  ON product_feed_items(source, brand_slug, product_slug)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_product_feed_items_brand_slug
  ON product_feed_items(brand_slug);

CREATE INDEX IF NOT EXISTS idx_product_feed_items_external_product_id
  ON product_feed_items(source, external_product_id);

-- Migration complete
